version: "3.9"

services:

  # ── FastAPI — Churn Prediction API ──────────────────────
  api:
    image: codex03080/churn-prediction-api:latest
    container_name: churn_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
    environment:
      # ✅ Pointing to DagsHub — no local mlflow container needed
      - MLFLOW_TRACKING_URI=https://dagshub.com/codex03080/Customer-Churn-Prediction-and-Business-Insights.mlflow
      - MLFLOW_TRACKING_USERNAME=codex03080
      - MLFLOW_TRACKING_PASSWORD=5eda9b2481b1ff77e21abc97468ef4d0ff3b75eb
    restart: unless-stopped
    # ✅ Removed depends_on mlflow — no local mlflow container anymore

volumes:
  mlflow_data: